server:
  port: 9001
spring:
  application:
    name: nacos-payment-server
  cloud:
    nacos:
      discovery:
        server-addr: locahost:8848
management:
  endpoints:
    web:
      exposure:
        exclude: '*'